version: '2.4'

services:
  dev:
    container_name: api_dev
    image: api-dev
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:dev
    ports:
      - '7001:7001'
    networks:
      - nestjs-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: unless-stopped

  build:
    image: api-dev
    command: npm run build && exit
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  prod:
    container_name: api_prod
    image: api-prod
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    command: npm run start:prod
    ports:
      - '7001:7001'
    networks:
      - nestjs-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: unless-stopped

networks:
  nestjs-network:
